// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: pkg/apis/lumberjust.proto

package apis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JustificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Audience string `protobuf:"bytes,1,opt,name=audience,proto3" json:"audience,omitempty"`
	Resource string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Role     string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Reason   string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Ticket   string `protobuf:"bytes,5,opt,name=ticket,proto3" json:"ticket,omitempty"`
}

func (x *JustificationRequest) Reset() {
	*x = JustificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_lumberjust_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JustificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JustificationRequest) ProtoMessage() {}

func (x *JustificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_lumberjust_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JustificationRequest.ProtoReflect.Descriptor instead.
func (*JustificationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_lumberjust_proto_rawDescGZIP(), []int{0}
}

func (x *JustificationRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *JustificationRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *JustificationRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *JustificationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *JustificationRequest) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

type JustificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *JustificationResponse) Reset() {
	*x = JustificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_lumberjust_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JustificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JustificationResponse) ProtoMessage() {}

func (x *JustificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_lumberjust_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JustificationResponse.ProtoReflect.Descriptor instead.
func (*JustificationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_lumberjust_proto_rawDescGZIP(), []int{1}
}

func (x *JustificationResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_pkg_apis_lumberjust_proto protoreflect.FileDescriptor

var file_pkg_apis_lumberjust_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x6c, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x6a, 0x75, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x6b, 0x67,
	0x2e, 0x61, 0x70, 0x69, 0x73, 0x22, 0x92, 0x01, 0x0a, 0x14, 0x4a, 0x75, 0x73, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x61, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x61, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x2d, 0x0a, 0x15, 0x4a, 0x75,
	0x73, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x5a, 0x0a, 0x0a, 0x4a, 0x75, 0x73,
	0x74, 0x49, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x4c, 0x0a, 0x07, 0x4a, 0x75, 0x73, 0x74, 0x69,
	0x66, 0x79, 0x12, 0x1e, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x4a, 0x75,
	0x73, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x4a, 0x75,
	0x73, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_apis_lumberjust_proto_rawDescOnce sync.Once
	file_pkg_apis_lumberjust_proto_rawDescData = file_pkg_apis_lumberjust_proto_rawDesc
)

func file_pkg_apis_lumberjust_proto_rawDescGZIP() []byte {
	file_pkg_apis_lumberjust_proto_rawDescOnce.Do(func() {
		file_pkg_apis_lumberjust_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_apis_lumberjust_proto_rawDescData)
	})
	return file_pkg_apis_lumberjust_proto_rawDescData
}

var file_pkg_apis_lumberjust_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_apis_lumberjust_proto_goTypes = []interface{}{
	(*JustificationRequest)(nil),  // 0: pkg.apis.JustificationRequest
	(*JustificationResponse)(nil), // 1: pkg.apis.JustificationResponse
}
var file_pkg_apis_lumberjust_proto_depIdxs = []int32{
	0, // 0: pkg.apis.JustInTime.Justify:input_type -> pkg.apis.JustificationRequest
	1, // 1: pkg.apis.JustInTime.Justify:output_type -> pkg.apis.JustificationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_apis_lumberjust_proto_init() }
func file_pkg_apis_lumberjust_proto_init() {
	if File_pkg_apis_lumberjust_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_apis_lumberjust_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JustificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_lumberjust_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JustificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_apis_lumberjust_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apis_lumberjust_proto_goTypes,
		DependencyIndexes: file_pkg_apis_lumberjust_proto_depIdxs,
		MessageInfos:      file_pkg_apis_lumberjust_proto_msgTypes,
	}.Build()
	File_pkg_apis_lumberjust_proto = out.File
	file_pkg_apis_lumberjust_proto_rawDesc = nil
	file_pkg_apis_lumberjust_proto_goTypes = nil
	file_pkg_apis_lumberjust_proto_depIdxs = nil
}
